"""chore: Revised email to be unique

Revision ID: 5ab39919d6d4
Revises: 31c1dad960d9
Create Date: 2025-04-22 12:00:33.544583

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5ab39919d6d4"
down_revision: Union[str, None] = "31c1dad960d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_account_email", table_name="account")
    op.create_index(op.f("ix_account_email"), "account", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_email"), table_name="account")
    op.create_index("ix_account_email", "account", ["email"], unique=False)
    # ### end Alembic commands ###
